### ISSUE TITLE
你这有问题啊（大恼）

### ISSUE THREAD

**Issue by BilShiziheng** [LYXOfficial/Hexo-theme-Acryple#14]
For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/

C:\Users\shizi\Hexo-theme-Acryple>hexo clean&&hexo g&&hexo s
INFO  Validating config
INFO  Hexo Acryple theme based Butterfly 4.2.2
============================================================
INFO  Validating config
INFO  Hexo Acryple theme based Butterfly 4.2.2
============================================================
INFO  Start processing
WARN  Tabs block must have unique name!
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
  TypeError: Cannot read properties of undefined (reading 'forEach')
    at Object._prettifyError (C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\node_modules\nunjucks\src\lib.js:36:11)
    at C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\node_modules\nunjucks\src\environment.js:563:19
    at Template.root [as rootRenderFunc] (eval at _compile (C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:53:3)
    at Template.render (C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\node_modules\nunjucks\src\environment.js:552:10)
    at Environment.renderString (C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\node_modules\nunjucks\src\environment.js:380:17)
    at C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\lib\extend\tag.js:238:16
    at tryCatcher (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.fromNode.Promise.fromCallback (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\promise.js:209:30)
    at Tag.render (C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\lib\extend\tag.js:237:20)
    at Object.onRenderEnd (C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\lib\hexo\post.js:426:22)
    at C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\lib\hexo\render.js:85:21
    at tryCatcher (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:471:21)

C:\Users\shizi\Hexo-theme-Acryple>hexo s
INFO  Validating config
INFO  Hexo Acryple theme based Butterfly 4.2.2
============================================================
FATAL Port 4000 has been used. Try other port instead.
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (node:net:1717:16)
    at listenInCluster (node:net:1765:12)
    at Server.listen (node:net:1853:7)
    at C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo-server\lib\server.js:68:12
    at Promise._execute (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\debuggability.js:384:9)
    at Promise._resolveFromExecutor (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\promise.js:518:18)
    at new Promise (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\promise.js:103:10)
    at checkPort (C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo-server\lib\server.js:65:10)
    at module.exports (C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo-server\lib\server.js:17:10)
    at Hexo.tryCatcher (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\method.js:15:34)
    at Hexo.call (C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\lib\hexo\index.js:258:27)
    at C:\Users\shizi\AppData\Roaming\npm\node_modules\hexo-cli\lib\hexo.js:60:17
    at tryCatcher (C:\Users\shizi\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\shizi\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\shizi\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\shizi\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\shizi\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\shizi\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\shizi\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\shizi\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Users\shizi\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:471:21)

C:\Users\shizi\Hexo-theme-Acryple>hexo s
INFO  Validating config
INFO  Hexo Acryple theme based Butterfly 4.2.2
============================================================
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
  TypeError: Cannot read properties of undefined (reading 'forEach')
    at Object._prettifyError (C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\node_modules\nunjucks\src\lib.js:36:11)
    at C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\node_modules\nunjucks\src\environment.js:563:19
    at Template.root [as rootRenderFunc] (eval at _compile (C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:53:3)
    at Template.render (C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\node_modules\nunjucks\src\environment.js:552:10)
    at Environment.renderString (C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\node_modules\nunjucks\src\environment.js:380:17)
    at C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\lib\extend\tag.js:238:16
    at tryCatcher (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.fromNode.Promise.fromCallback (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\promise.js:209:30)
    at Tag.render (C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\lib\extend\tag.js:237:20)
    at Object.onRenderEnd (C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\lib\hexo\post.js:426:22)
    at C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\lib\hexo\render.js:85:21
    at tryCatcher (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:471:21)

C:\Users\shizi\Hexo-theme-Acryple>hexo s
INFO  Validating config
INFO  Hexo Acryple theme based Butterfly 4.2.2
============================================================
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
  TypeError: Cannot read properties of undefined (reading 'forEach')
    at Object._prettifyError (C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\node_modules\nunjucks\src\lib.js:36:11)
    at C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\node_modules\nunjucks\src\environment.js:563:19
    at Template.root [as rootRenderFunc] (eval at _compile (C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:53:3)
    at Template.render (C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\node_modules\nunjucks\src\environment.js:552:10)
    at Environment.renderString (C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\node_modules\nunjucks\src\environment.js:380:17)
    at C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\lib\extend\tag.js:238:16
    at tryCatcher (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.fromNode.Promise.fromCallback (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\promise.js:209:30)
    at Tag.render (C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\lib\extend\tag.js:237:20)
    at Object.onRenderEnd (C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\lib\hexo\post.js:426:22)
    at C:\Users\shizi\Hexo-theme-Acryple\node_modules\hexo\lib\hexo\render.js:85:21
    at tryCatcher (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Users\shizi\Hexo-theme-Acryple\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:471:21)

C:\Users\shizi\Hexo-theme-Acryple>
真TM服了
（话说周末为什么不回复我评论（大嘘））

**Comment by Ezgx** [comment]
![image](https://user-images.githubusercontent.com/110729988/212578441-6bb526f0-e132-492f-a413-146c3a59c0d7.png)
第一个是啥东西的路径戳啦
![image](https://user-images.githubusercontent.com/110729988/212578504-d20c2be9-a318-4c43-87ca-2836544d0180.png)
第二个是你在其他地方开了hexo了，端口4000被占用

**Comment by BilShiziheng** [comment]
我选择typecho+handsome(

**Comment by Ezgx** [comment]
> 我选择typecho+handsome(

6
